# Generated by Django 4.2.7 on 2025-06-16 08:01

from django.db import migrations, models


def set_room_id_from_room(apps, schema_editor):
    """
    Set room_id values for existing messages based on room field.
    If room field can be converted to an integer, use that value.
    Otherwise, use a default value of 1.
    """
    ChatMessage = apps.get_model('chat', 'ChatMessage')
    for message in ChatMessage.objects.all():
        try:
            message.room_id = int(message.room)
        except (ValueError, TypeError):
            message.room_id = 1
        message.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        # First ensure room_id is nullable to avoid errors
        migrations.AlterField(
            model_name='chatmessage',
            name='room_id',
            field=models.IntegerField(null=True),
        ),
        # Run the data migration to populate room_id values
        migrations.RunPython(set_room_id_from_room),
        # Then make room_id non-nullable
        migrations.AlterField(
            model_name='chatmessage',
            name='room_id',
            field=models.IntegerField(),
        ),
    ]
