# Generated by Django 4.2.7 on 2025-06-16 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_chatmessage_parent_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatreaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatreaction',
            name='custom_reaction',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='chatreaction',
            name='reaction',
            field=models.CharField(choices=[('👍', 'Thumbs Up'), ('👎', 'Thumbs Down'), ('❤️', 'Heart'), ('😂', 'Laugh'), ('😮', 'Wow'), ('😢', 'Sad'), ('😡', 'Angry'), ('custom', 'Custom')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='chatreaction',
            unique_together={('message', 'user', 'reaction')},
        ),
        migrations.CreateModel(
            name='ReactionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=20)),
                ('room_id', models.IntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('reaction', 'room_id')},
            },
        ),
    ]
