# Generated by Django 4.2.7 on 2025-06-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatreaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
